fs/erofs: Fix build for m68k
Currently the use of roundup() causes GCC to emit a reference
to __udivdi3() on m68k and we don't have that:

/usr/bin/m68k-linux-gnu-ld.bfd: fs/erofs/data.o: in function `erofs_map_blocks':
u-boot/fs/erofs/data.c:81:(.text.erofs_map_blocks+0x126): undefined reference to `__udivdi3'
/usr/bin/m68k-linux-gnu-ld.bfd: u-boot/fs/erofs/data.c:81:(.text.erofs_map_blocks+0x458): undefined reference to `__udivdi3'

We could add it but since unit is 4 or 8 we can actually just
switch the code to use round_up() instead and not output
__udivdi3() in the first place.

Signed-off-by: Daniel Palmer <daniel@thingy.jp>